env:
  ANKA_IMAGE_NAME: aug16sierra
  XCODE_DESTINATION: platform=iOS Simulator,name=iPhone 7,OS=11.0

steps:
  - label: "Build"
    command: "./build.sh"

  - wait
  - label: "Unit Tests"
    command: "./test.sh 'Buildkite Anka DemoTests'"

  - wait
  - label: "UI Tests"
    command: "./test.sh 'Buildkite Anka DemoUITests'"
